### ISSUE TITLE
load fbx get a Exception

### ISSUE THREAD

**Issue by qq1053831109** [stephengold/MonkeyWrench#1]
java.lang.IllegalStateException: Asset implements CloneableSmartAsset but doesn't have processor to handle cloning
	at com.jme3.asset.DesktopAssetManager.registerAndCloneSmartAsset(DesktopAssetManager.java:327)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:394)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:402)
	at TestFbx.initApp(TestFbx.java:22)

**Comment by qq1053831109** [comment]
loadAsset
